- platform: template
  sensors:
    front_door:
      friendly_name: "Front Door"
      value_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d0001596697', 'off') %}
            Closed
          {% elif is_state('binary_sensor.door_window_sensor_158d0001596697', 'on') %}
            Open
          {% else %}
            failed
          {% endif %}
      icon_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d0001596697', 'off') %}
            mdi:door-closed
          {% elif is_state('binary_sensor.door_window_sensor_158d0001596697', 'on') %}
            mdi:door-open
          {% endif %}