- platform: history_stats
  name: Time spent watching TV
  entity_id: media_player.tv_2
  state: 'playing'
  type: time
  start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
  end: '{{ now() }}'    
